### ISSUE TITLE
빌드에서의 무한 로딩문제

### ISSUE THREAD

**Issue by KwonTF** [ssu-esc/be#17]
개발버젼은 상관없는데 빌드버젼으로
localhost:5000으로 들어가면 무한로딩이 걸림 내가 뭐 따로 설정 해야 하는게 있나?

이게 직접 127.0. 어쩌구로 직접 치면 잘 들어가지는 대신에 로그인이 안됨

**Comment by niceb5y** [comment]
데이터베이스 환경변수 같은거 설정해야할텐데

**Comment by niceb5y** [comment]
일단 해결
